language: php

sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 7.0

before_install:
  - travis_retry composer.phar selfupdate

install:
  - travis_retry composer update --prefer-source

script:
  - ./vendor/bin/phpspec run --format=pretty
